config/routes.rb
Mentorme::Application.routes.draw do
  resources :profiles do
    collection do
      get :search
    end
  end

  get "welcome/index"

   root 'welcome#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
validates :name, :email, presence: true
validates :post_code, length: { is: 4 }

	def self.search(search, person)
	  search_condition = "%" + search + "%"
	  search_results = where(['
	  	name LIKE ? OR
	  	category LIKE ? OR
	  	post_code LIKE ? OR
	  	tag_line LIKE ? OR
	  	email LIKE ? OR
	  	short_biography LIKE? OR
	  	what_do_you_want_to_achieve LIKE?',
	  	search_condition, search_condition, search_condition, search_condition, search_condition, search_condition, search_condition
	  	])

	  if (person == "mentor")
	  	search_results.where :mentor => true
	  elsif (person == "mentee")
	  	search_results.where :mentee => true
	  else
	  	search_results
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end

  def search
    @profiles = Profile.search params[:search], params[:person]
    render 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :mentor, :mentee, :post_code, :email, :tag_line, :meet_up, :catagory, :short_biography, :what_do_you_want_to_achieve)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	render layout: false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(profile)
    gravatar_id = Digest::MD5::hexdigest(profile.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: profile.name, class: "gravatar")
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mentorme</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Asul' rel='stylesheet' type='text/css'>

</head>
<body>
<div class="container">
	<div class = "container-fluid">
	<% unless notice.blank? %>
		<span id="notice"><%= notice %></span>
	<% end %>
		<div class = "row">
	  		<div class = "col-xs-12 navigation">
	  		<%= link_to 'Home', root_path %>
	  		<%= yield :page_nav %>
	  		</div>
		</div>
		<div class = "row main">
			<div class = "col-xs-12 search col-md-3">
			<h1>Search for profiles</h1>
			  <div id="search">
			    <%= render :partial => 'profiles/search' %>
			  </div>
			</div>
			<div class = "col-xs-12 col-md-9 profile">
				<%= yield %>
			</div>
		</div>
	</div>
</div>
</body>
</html>

app/views/profiles/_form.html.erb
<%= form_for(@profile, :class => "form-control form-horizontal") do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="field form-group checkbox">
    <%= f.label :mentor %>
    <%= f.check_box :mentor %>
  </div>
  <div class="field form-group checkbox">
    <%= f.label :mentee %>
    <%= f.check_box :mentee %>
  </div>
  <div class="field form-group">
    <%= f.label :post_code %><br>
    <%= f.text_field :post_code, :class => "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, :class => "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :tag_line %><br>
    <%= f.text_field :tag_line, :class => "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :meet_up %><br>
    <%= f.text_field :meet_up, :class => "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :category %><br>
    <%= f.text_field :category, :class => "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :short_biography %><br>
    <%= f.text_area :short_biography, :class => "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :what_do_you_want_to_achieve %><br>
    <%= f.text_area :what_do_you_want_to_achieve, :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-default'%>
  </div>
<% end %>

app/views/profiles/_search.erb
<%= form_tag({:controller => 'profiles', :action => 'search'}, {:method => :get, :class => "form-horizontal"}) do %>
<div class="form-group">
    <%= text_field_tag :search, params[:search], :id => 'search_field', :class => "form-control" %>
    <%= link_to_function "Clear", "$('#search_field').val('')" %>
</div>
<div class="form-group">
	<div class="radio">
    <%= label_tag :person_mentor, "Mentor" %><%= radio_button_tag :person, :mentor, params[:person]=="mentor" %>
    </div>
    <div class="radio">
    <%= label_tag :person_mentee, "Mentee" %><%= radio_button_tag :person, :mentee, params[:person]=="mentee" %>
    </div>
    <div class="radio">
    <%= label_tag :person_all, "All" %><%= radio_button_tag :person, :all, params[:person]=="all" %>
    </div>
</div>
    <%= submit_tag "Search", :class => "btn btn-default", :name => nil %>
<% end %>
<div>
<%= button_to "Reset", profiles_path, :class => "btn btn-default", :method => :get %>
</div>

app/views/profiles/edit.html.erb
<% content_for :page_nav do %>
  <%= link_to 'Show', @profile %>
  <%= link_to 'Back', profiles_path %>
<% end %>

<h1>Editing profile</h1>

<%= render 'form' %>

app/views/profiles/index.html.erb
<% content_for :page_nav do %>
  <%= link_to 'New Profile', new_profile_path %>
<% end %>

<h1>Listing profiles</h1>

<% @profiles.each do |profile| %>
<div class = "col-xs-12 mentee">
  <div class = "col-xs-3 avatar">
    <%= gravatar_for profile unless profile.email.blank? %>
    <ul>
      <li><%= link_to profile.name, profile %></li>
      <li><%= profile.tag_line %></li>
      <%= link_to 'Delete', profile, method: :delete, data: { confirm: 'Are you sure?' } %>
    </ul>
  </div>
  <div class = "col-xs-6 description">
    <ul>
      <%= content_tag(:li) do
        "I want to meet at: #{profile.meet_up}"
      end unless profile.meet_up.blank? %>

      <%= content_tag(:li) do
        "I know lots about: #{profile.category}"
      end unless profile.category.blank? %>

      <%= content_tag(:li) do
        "A bit about me: #{profile.short_biography}"
      end unless profile.short_biography.blank? %>

      <%= content_tag(:li) do
        "I would like to achieve: #{profile.what_do_you_want_to_achieve}"
      end unless profile.what_do_you_want_to_achieve.blank? %>

      </ul>
  </div>
</div>
<% end %>

app/views/profiles/new.html.erb
<% content_for :page_nav do %>
  <%= link_to 'Back', profiles_path %>
<% end %>

<h1>New profile</h1>

<%= render 'form' %>

app/views/profiles/show.html.erb
<% content_for :page_nav do %>
  <%= link_to 'Edit', edit_profile_path(@profile) %>
  <%= link_to 'Back', profiles_path %>
<% end %>

<p>
  <%= gravatar_for @profile %>
</p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Mentor:</strong>
  <%= @profile.mentor %>
</p>

<p>
  <strong>Mentee:</strong>
  <%= @profile.mentee %>
</p>

<p>
  <strong>Post code:</strong>
  <%= @profile.post_code %>
</p>

<p>
  <strong>Email:</strong>
  <%= @profile.email %>
</p>

<p>
  <strong>Tag line:</strong>
  <%= @profile.tag_line %>
</p>

<p>
  <strong>Meet up:</strong>
  <%= @profile.meet_up %>
</p>

<p>
  <strong>Category:</strong>
  <%= @profile.category %>
</p>

<p>
  <strong>Short biography:</strong>
  <%= @profile.short_biography %>
</p>

<p>
  <strong>What do you want to achieve:</strong>
  <%= @profile.what_do_you_want_to_achieve %>
</p>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mentorme</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Asul' rel='stylesheet' type='text/css'>
	<script> var SSOobjParams = {} </script>
	<script src="http://www.slijs.com/assets/sso.js"></script>
</head>
<body>
<div class="container">
	<div id="welcome_page">
	<h1>Coffee house Mentor</h1>
	</div>

	<div class="sign_in_page">
	<h2>Create a profile and find your perfect mentor today!</h2>

	<a href="/profiles/new" class="ssosignin btn btn-default">Sign In</a>
	<p>Create a profile and start finding your match</p><br>
	<a href="/profiles" class="btn btn-default">Tour In</a>
	<p>Take a look at our great mentors and mentees</p>
	</div>
</div>
</body>
</html>